[package]
name = "ipvm"
version = "0.1.0"
description = ""
keywords = []
categories = []
include = ["/src", "/examples", "/benches", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "Apache-2.0 or MIT"
readme = "README.md"
edition = "2021"
rust-version = "1.64"
documentation = "https://docs.rs/ipvm"
repository = "https://github.com/ipvm-wg/ipvm"
authors = ["Brooklyn Zelenka <hello@brooklynzelenka.com>"]

[lib]
path = "src/lib.rs"
bench = false

[[bench]]
name = "a_benchmark"
harness = false
required-features = ["test_utils"]

[[example]]
name = "counterparts"
path = "examples/counterparts.rs"

[dependencies]
anyhow = "1.0"
proptest = { version = "1.0", optional = true }
tracing = "0.1"

[dev-dependencies]
criterion = "0.4"

[features]
default = []
test_utils = ["proptest"]

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
